In [0]:
'''
Linear Regression: Nithin
Lasso Regression: nithin
SVM: yunhao
Neural Net (in folder rlp_regresssion_result): Jay
RadiusNeighborsRegression: yunhao
RANSCARRegressor: Jay
'''

'\nLinear Regression: Nithin\nLasso Regression: nithin\nSVM: yunhao\nNeural Net (in folder rlp_regresssion_result): Jay\nRadiusNeighborsRegression: yunhao\nRANSCARRegressor: Jay\n'

In [0]:
import pandas as pd
import numpy as np
import sklearn.preprocessing as prep
import sklearn.pipeline as pl
import sklearn.svm as sv
import sklearn.neighbors as nei
import sklearn.metrics as mt
import sklearn.model_selection as ms
import matplotlib.pyplot as plt
import warnings
import sklearn.neural_network as nn
from sklearn.linear_model import RANSACRegressor
warnings.simplefilter("ignore")

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
cwd = 'drive/My Drive/data mining project/'
unlabeled_cwd = 'drive/My Drive/data mining project/unlabeled data/'
result_cwd = cwd + 'final result/'
sector_list = pd.read_csv('drive/My Drive/data mining project/sector_list.csv', header=None)

regressions = ['radius_nearest_neignbor_regression', 'sv_regression', 'rlp_regression', 'RANSAC_regression', 'lasso_regression', 'linear_regression']

# Read in result files

## read mean square errors

In [0]:
init_mse = pd.read_csv(cwd + 'Initial_MSE.csv', header=None, names=['industry', 'mse'])

rnr_mse = pd.read_csv(cwd + regressions[0] + '_result/mse.csv', header=None)
svr_mse = pd.read_csv(cwd + regressions[1] + '_result/mse.csv', header=None)
rlp_mse = pd.read_csv(cwd + regressions[2] + '_result/mse.csv', header=None)
ran_mse = pd.read_csv(cwd + regressions[3] + '_result/mse.csv', header=None)
lasso_mse = pd.read_csv(cwd + regressions[4] + '_result/mse.csv', header=None)
linear_mse = pd.read_csv(cwd + regressions[5] + '_result/mse.csv', header=None)

mse = [rnr_mse, svr_mse, rlp_mse, ran_mse, lasso_mse, linear_mse]
init_mse.head(30)

                                          industry            mse
0                     Accomodation & Food Services      35.357177
1                                Arts & Recreation     405.041865
2          Asset Management & Securities Brokerage      30.017355
3                                            Banks       9.719772
4                        Business Support Services     688.572714
5                                Chemical Products     379.276387
6                  Computer Hardware & Electronics      79.443579
7                                    Conglomerates      11.287251
8                                     Construction      15.845251
9                                Consumer Services     318.958884
10                            Educational Services       6.449166
11        Food, Beverages, & Tobacco Manufacturing      70.498799
12                          Forestry & Agriculture      14.039632
13              Furniture & Textiles Manufacturing      34.595290
14                 Health Care & Social Assistance       9.182921
15                            Information Services     362.550224
16                     Insurance Brokerage & Other     110.442382
17                           Manufacturing (Misc.)     200.477883
18            Merchant Wholesalers - Durable Goods     108.994436
19        Merchant Wholesalers - Non-Durable Goods    1793.402601
20                             Minerals Extraction    1269.997565
21                        Non-Bank Credit Services      20.462229
22                                 Pharmaceuticals    8230.478836
23  Professional, Scientific, & Technical Services     118.373806
24                                     Real Estate  118327.688218
25                              Rental and Leasing     112.266767
26                                Specialty Retail     439.827289
27               Supermarkets & Convenience Stores     116.098368
28                                  Transportation     147.562845
29                                       Utilities      94.872265

## determine the best regressor for each industry

In [0]:
report_list = []

In [0]:
for industry in sector_list.iterrows():
  ind_name = industry[1][0]
  ind_index = industry[0]
  min_mse = init_mse['mse'][ind_index]
  mse_initial = min_mse
  best_reg = None
  
  # loop through all the regressors to find the one with minimum mse
  reg_idx = 0
  for reg in regressions:
    reg_mse = mse[reg_idx][0][ind_index]
    if min_mse > reg_mse:
      min_mse = reg_mse
      best_reg = regressions[reg_idx]
    reg_idx += 1

  result = pd.read_csv(cwd + best_reg + '_result/' + ind_name + '.csv', header=None)
  unlabel_data = pd.read_csv(unlabeled_cwd + ind_name + '.csv')
  unlabel_data['future_net_income_growth'] = result[0]
  unlabel_data = unlabel_data[['symbol', 'industry', 'period_end_date', 'future_net_income_growth']].sort_values(by='future_net_income_growth', ascending=False)
  
  unlabel_data.to_csv(result_cwd + ind_name + '_result.csv', index=None)

  # add a report
  report_list.append([ind_name, best_reg, min_mse, mse_initial])

## add a report of regressors

In [0]:
report_df = pd.DataFrame(report_list, columns=['Industry', 'Best Regressor', 'MSE with Best Reg', 'MSE with naive predict'])
report_df.to_csv(cwd + 'Error_Report.csv', index=None)
report_df.head(30)

                                          Industry  ... MSE with naive predict
0                     Accomodation & Food Services  ...              35.357177
1                                Arts & Recreation  ...             405.041865
2          Asset Management & Securities Brokerage  ...              30.017355
3                                            Banks  ...               9.719772
4                        Business Support Services  ...             688.572714
5                                Chemical Products  ...             379.276387
6                  Computer Hardware & Electronics  ...              79.443579
7                                    Conglomerates  ...              11.287251
8                                     Construction  ...              15.845251
9                                Consumer Services  ...             318.958884
10                            Educational Services  ...               6.449166
11        Food, Beverages, & Tobacco Manufacturing  ...              70.498799
12                          Forestry & Agriculture  ...              14.039632
13              Furniture & Textiles Manufacturing  ...              34.595290
14                 Health Care & Social Assistance  ...               9.182921
15                            Information Services  ...             362.550224
16                     Insurance Brokerage & Other  ...             110.442382
17                           Manufacturing (Misc.)  ...             200.477883
18            Merchant Wholesalers - Durable Goods  ...             108.994436
19        Merchant Wholesalers - Non-Durable Goods  ...            1793.402601
20                             Minerals Extraction  ...            1269.997565
21                        Non-Bank Credit Services  ...              20.462229
22                                 Pharmaceuticals  ...            8230.478836
23  Professional, Scientific, & Technical Services  ...             118.373806
24                                     Real Estate  ...          118327.688218
25                              Rental and Leasing  ...             112.266767
26                                Specialty Retail  ...             439.827289
27               Supermarkets & Convenience Stores  ...             116.098368
28                                  Transportation  ...             147.562845
29                                       Utilities  ...              94.872265

[30 rows x 4 columns]